In [6]:
import numpy as np
import torch

In [10]:
x = np.zeros([2,2,3])
x = torch.zeros([2,2,3])

In [46]:
x = torch.arange(4)
length = torch.tensor([[2,3,3,0],[1,3,1,0]])

In [51]:
length.size()

torch.Size([2, 4])

In [31]:
x.unsqueeze(0) < length.unsqueeze(1)

tensor([[[ True,  True,  True, False]],

        [[ True,  True, False, False]]])

In [26]:
x.unsqueeze(0)

tensor([[0, 1, 2, 3]])

In [27]:
length.unsqueeze(1)

tensor([[[2, 3, 2, 0]],

        [[1, 3, 0, 0]]])

In [45]:
x = np.array([1,3])
y = np.array([True, False])

x*y

array([1, 0])

In [1]:
reversed(x)

NameError: name 'x' is not defined